CREATE TABLE test.apartments
(   id INT AUTO_INCREMENT PRIMARY KEY,
    Apartments	VARCHAR(255),
    SwimmingPool	TINYINT,
    BBQGrill	TINYINT,
    FiresideSeating	TINYINT,
    CommunityGarden	TINYINT,
    Gym	TINYINT,
    BasketBallCourt	TINYINT,
    TennisCourt	TINYINT,
    RooftopLounge	TINYINT,
    Clubhouse	TINYINT,
    BusinessRoom	TINYINT,
    Gameroom	TINYINT,
    CofeeBar	TINYINT,
    EVCharger	TINYINT,
    SkylineViews	TINYINT,
    PackageLockers	TINYINT,
    Elevators	TINYINT,
    AllowPets	TINYINT,
    DogPark	TINYINT,
    DownwashStation	TINYINT,
    ParkingAvailable	TINYINT,
    CoveredParking	TINYINT,
    GarageParking	TINYINT,
    BikeStalls	TINYINT,
    FirePlace	TINYINT,
    HighCeilings	TINYINT,
    CeilingFans	TINYINT,
    PremiumLighting	TINYINT,
    GraniteCounterTops	TINYINT,
    IslandKitchen	TINYINT,
    StainlessSteelAppliances	TINYINT,
    WasherDryer	TINYINT
);